# Use an official Ubuntu as a parent image
FROM ubuntu:20.04

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install prerequisites including software-properties-common and build tools
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    python3-dev \
    python3-pip \
    python3.9 \
    python3.9-venv \
    python3.9-dev \
    x11-apps \
    libgl1-mesa-glx \
    libnss3 \
    libxcomposite1 \ 
    libxdamage1 \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    libxfixes-dev \
    libxi-dev \
    libxtst-dev \
    libxrandr-dev \
    libxcursor-dev \
    libxcomposite-dev \
    libxdamage-dev \
    libxinerama-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libglib2.0-0 \
    libxcb-xinerama0 \
    # python3-pyqt5 \ 
    && rm -rf /var/lib/apt/lists/*


# Set the working directory in the container
WORKDIR /src

# Copy the requirements.txt file and install dependencies
COPY requirements.txt .
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -r requirements.txt -i https://pypi.org/simple

# Copy the current directory contents into the container at /app
COPY . /src

# Command to run your PyQt application
CMD ["bash"]
